name: Autograded C tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup GCC
        uses: actions/setup-gcc@v1

      - name: Build and run tests
        run: |
          make

